// Tests for the AI Creator EXTENSION PAGE (extension/ai-creator/) — Phase 3
// frontend wiring. The extension has no test infrastructure of its own (no
// framework, no test files); following this repo's own precedent
// (replayEngine.e2e.test.js already loads real extension/content/content.js
// into a Playwright page via a fixture harness), this loads the REAL
// ai-creator.html/.css/.js over file:// in a real headless Chromium, with
// chrome.storage/chrome.runtime shimmed (there is no real extension
// context outside Chrome) and every backend call intercepted via
// page.route() — no live backend, no live Ollama, ever required.
//
// Two conceptually different example intents (flight vs. hotel/search) are
// used throughout specifically to prove the page renders whatever
// parameters the backend returns, with no task-specific frontend code.
//
// Run with: node backend/test/aiCreatorPage.test.js
process.env.NODE_ENV = process.env.NODE_ENV || 'test';

const assert = require('assert');
const path = require('path');
const { pathToFileURL } = require('url');
const { chromium } = require('playwright');

const PAGE_URL = pathToFileURL(path.join(__dirname, '..', '..', 'extension', 'ai-creator', 'ai-creator.html')).href;

const results = [];
const test = async (name, fn) => {
  const started = Date.now();
  try {
    await fn();
    results.push({ name, ok: true, ms: Date.now() - started });
    console.log(`  ✓ ${name} (${Date.now() - started}ms)`);
  } catch (error) {
    results.push({ name, ok: false, ms: Date.now() - started, error });
    console.log(`  ✗ ${name} (${Date.now() - started}ms)`);
    console.log(`      ${error.message}`);
  }
};

// --- Fixtures ---------------------------------------------------------

const FLIGHT_INTENT = {
  targetSite: { name: 'FlightRadar24', url: 'https://www.flightradar24.com', confidence: 0.9, needsConfirmation: false },
  task: 'Search for flights',
  parameters: [
    { name: 'origin', type: 'text', value: 'Dhaka', label: 'Origin', description: 'Departure location' },
    { name: 'destination', type: 'text', value: 'Dubai', label: 'Destination', description: 'Arrival location' }
  ]
};

// Deliberately a totally different shape (city/date/number instead of
// origin/destination) — proves nothing in the page assumes flight-shaped
// parameters. Also needsConfirmation: true, to exercise that gate.
const HOTEL_INTENT = {
  targetSite: { name: 'Booking.com', url: 'https://www.booking.com', confidence: 0.4, needsConfirmation: true },
  task: 'Search hotels',
  parameters: [
    { name: 'city', type: 'text', value: "Cox's Bazar", label: 'City', description: 'Hotel destination' },
    { name: 'check_in', type: 'date', value: '2026-09-10', label: 'Check-in', description: 'Hotel check-in date' },
    { name: 'nights', type: 'number', value: '3', label: 'Number of nights', description: 'Length of stay' }
  ]
};

let sessionCounter = 1000;
const makeSession = ({ sessionId, status = 'awaiting_confirmation', nlCommand = 'test command', intent = null, generatedWorkflowId = null, extraMessages = [] } = {}) => ({
  sessionId: String(sessionId || (sessionCounter += 1)),
  status,
  nlCommand,
  messages: [
    { role: 'user', text: nlCommand, at: new Date().toISOString() },
    ...(intent ? [{ role: 'assistant', type: 'intent', intent, at: new Date().toISOString() }] : []),
    ...extraMessages
  ],
  intent,
  generatedWorkflowId,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString()
});

// A deliberately ARBITRARY result dataset — the field names (alpha/beta/gamma)
// are nonsense on purpose, to prove the panel renders whatever JSON the backend
// returns with zero field-specific frontend code (no product_name/price/etc.).
const GENERIC_RESULTS = {
  data: [
    { alpha: 'one', beta: 42, gamma: 'x' },
    { alpha: 'two', beta: 7, gamma: 'y' },
    { alpha: 'three', beta: 13, gamma: 'z' }
  ],
  totalFound: 3,
  confidence: 0.7,
  extractionMethod: 'dom',
  truncated: false,
  source: 'https://example.test/results'
};

const myApiFor = (id, workflowId) => ({
  id, ownerId: 1, workflowId: String(workflowId), name: 'Search for flights', version: 'v1.0', method: 'POST',
  endpoint: `/api/workflows/${workflowId}/run`, description: 'Generated by the AI API Creator', parameters: FLIGHT_INTENT.parameters,
  price: 0, published: false, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString()
});

// Matchers driving a session all the way to a COMPLETED generation whose
// /generate response carries `results` (or null). `results` is passed straight
// through so a test can exercise a populated dataset, an empty one, or none.
const completedGenerateMatchers = ({ sessionId, myApiId, workflowId, results }) => ([
  { test: (url, m) => url.endsWith('/api/ai-creator/sessions') && m === 'POST', respond: (route) => fulfillJson(route, 201, { success: true, ...makeSession({ sessionId, intent: FLIGHT_INTENT }) }) },
  {
    test: (url, m) => url.endsWith(`/api/ai-creator/sessions/${sessionId}/generate`) && m === 'POST',
    respond: (route) => fulfillJson(route, 200, {
      success: true, ...makeSession({ sessionId, status: 'completed', intent: FLIGHT_INTENT, generatedWorkflowId: String(workflowId) }),
      workflowId: String(workflowId), myApiId, endpoint: `/api/workflows/${workflowId}/run`, method: 'POST', stepCount: 2, results
    })
  },
  { test: (url, m) => url.endsWith(`/api/my-apis/${myApiId}`) && m === 'GET', respond: (route) => fulfillJson(route, 200, myApiFor(myApiId, workflowId)) }
]);

const generateThenComplete = async (page) => {
  await page.fill('#ai-input', 'Create an API to search for flights from Dhaka to Dubai.');
  await page.click('#send-btn');
  await page.waitForSelector('#generate-btn');
  await page.click('#generate-btn');
  await page.waitForSelector('#result-area:not([hidden])');
};

// --- Harness ------------------------------------------------------------

const seedChromeShim = (authToken) => {
  window.__ffStorage = authToken
    ? { 'forgeflow.auth': { token: authToken, user: { id: 1, email: 'test@example.com', name: 'Test User' } } }
    : {};
  window.chrome = {
    storage: {
      local: {
        get: (key, cb) => {
          if (typeof key === 'string') { cb({ [key]: window.__ffStorage[key] }); } else { cb({ ...window.__ffStorage }); }
        },
        set: (obj, cb) => { Object.assign(window.__ffStorage, obj); if (cb) cb(); },
        remove: (key, cb) => { delete window.__ffStorage[key]; if (cb) cb(); }
      }
    },
    runtime: { getURL: (p) => p }
  };
};

const fulfillJson = (route, status, body) => route.fulfill({ status, contentType: 'application/json', body: JSON.stringify(body) });

// Builds a page.route handler from an ordered list of
// { test: (url, method) => bool, respond: async (route, request) => void }
// matchers, recording every intercepted request into `calls`, falling back
// to an innocuous 200 for anything unmatched (e.g. notifications.js's own
// background poll) so unrelated shared scripts never error the page out.
const makeRouter = (matchers) => {
  const calls = [];
  const handler = async (route) => {
    const request = route.request();
    const url = request.url();
    const method = request.method();
    calls.push({ url, method, postData: request.postData() });
    for (const m of matchers) {
      if (m.test(url, method)) {
        await m.respond(route, request);
        return;
      }
    }
    await fulfillJson(route, 200, { success: true });
  };
  return { handler, calls };
};

let browser;

// authToken: null to test the logged-out gate; a string otherwise.
// matchers: backend route handlers (see makeRouter).
// speech: 'fake' | 'unsupported' | undefined (leave real headless Chromium behavior alone)
const withPage = async ({ authToken = 'test-token', matchers = [], speech } = {}, fn) => {
  const context = await browser.newContext();
  const page = await context.newPage();

  await page.addInitScript(seedChromeShim, authToken);
  if (speech === 'fake') {
    await page.addInitScript(() => {
      window.__recognitionInstances = [];
      class FakeRecognition extends EventTarget {
        start() { window.__recognitionInstances.push(this); this.dispatchEvent(new Event('start')); }
        stop() { this.dispatchEvent(new Event('end')); }
      }
      window.SpeechRecognition = FakeRecognition;
      delete window.webkitSpeechRecognition;
    });
  } else if (speech === 'unsupported') {
    await page.addInitScript(() => {
      Object.defineProperty(window, 'SpeechRecognition', { value: undefined, configurable: true });
      Object.defineProperty(window, 'webkitSpeechRecognition', { value: undefined, configurable: true });
    });
  }

  const { handler, calls } = makeRouter(matchers);
  await page.route('http://localhost:5000/**', handler);

  await page.goto(PAGE_URL, { waitUntil: 'domcontentloaded' });
  // ai-creator.js's own DOMContentLoaded init (auth check) has finished once
  // the input is no longer in its initial disabled-by-default state AND the
  // script has had a chance to run — waiting on the mic button's final
  // disabled/enabled state (set synchronously at the end of init, after the
  // auth await) is a reliable "page is ready" signal for both branches.
  await page.waitForFunction(() => document.getElementById('mic-btn') !== null);
  await page.waitForTimeout(50); // let the auth-check microtask queue drain

  try {
    await fn(page, calls);
  } finally {
    await context.close();
  }
};

const run = async () => {
  browser = await chromium.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage', '--disable-gpu']
  });

  await test('page loads and shows the empty-state prompt when no conversation exists yet', async () => {
    await withPage({}, async (page) => {
      await assert.doesNotReject(page.title());
      const emptyVisible = await page.isVisible('#chat-empty');
      assert.ok(emptyVisible, 'expected the empty-state prompt to be visible with no session yet');
      const inputDisabled = await page.$eval('#ai-input', (el) => el.disabled);
      assert.strictEqual(inputDisabled, false);
    });
  });

  await test('with no auth token, the input is disabled and the auth note is shown', async () => {
    await withPage({ authToken: null }, async (page) => {
      const noteHidden = await page.$eval('#auth-note', (el) => el.hidden);
      assert.strictEqual(noteHidden, false);
      const inputDisabled = await page.$eval('#ai-input', (el) => el.disabled);
      assert.strictEqual(inputDisabled, true);
    });
  });

  await test('sending a typed command calls POST /api/ai-creator/sessions with the command, and renders the confirmation area', async () => {
    const session = makeSession({ nlCommand: 'Create an API to search for flights from Dhaka to Dubai.', intent: FLIGHT_INTENT });
    const matchers = [{
      test: (url, method) => url.endsWith('/api/ai-creator/sessions') && method === 'POST',
      respond: (route, request) => {
        const body = JSON.parse(request.postData());
        assert.strictEqual(body.command, 'Create an API to search for flights from Dhaka to Dubai.');
        return fulfillJson(route, 201, { success: true, ...session });
      }
    }];

    await withPage({ matchers }, async (page, calls) => {
      await page.fill('#ai-input', 'Create an API to search for flights from Dhaka to Dubai.');
      await page.click('#send-btn');
      await page.waitForSelector('#confirm-area:not([hidden])');

      const createCalls = calls.filter((c) => c.url.endsWith('/api/ai-creator/sessions') && c.method === 'POST');
      assert.strictEqual(createCalls.length, 1, 'expected exactly one create-session call');

      const target = await page.textContent('.ai-confirm-row-value');
      assert.ok(target.includes('FlightRadar24'));
    });
  });

  // Regression test for the reported bug: the user's message must appear
  // the instant Send is clicked, not only once the (possibly multi-minute,
  // Ollama-backed) backend round-trip completes. Holds the real
  // POST /api/ai-creator/sessions response open to prove the message and a
  // genuine loading state render BEFORE any response exists, using the
  // exact backend response shape POST /api/ai-creator/sessions actually
  // returns (see makeSession/formatSession), not an invented one.
  await test('the user\'s message renders immediately on Send, before the backend responds, with a genuine (non-fake) loading state', async () => {
    let releaseCreate;
    const gate = new Promise((resolve) => { releaseCreate = resolve; });
    const session = makeSession({ nlCommand: 'Create an API to search hotels in Cox\'s Bazar.', intent: HOTEL_INTENT });

    const matchers = [{
      test: (url, m) => url.endsWith('/api/ai-creator/sessions') && m === 'POST',
      respond: async (route) => { await gate; await fulfillJson(route, 201, { success: true, ...session }); }
    }];

    await withPage({ matchers }, async (page, calls) => {
      await page.fill('#ai-input', 'Create an API to search hotels in Cox\'s Bazar.');
      await page.click('#send-btn');

      // Before the backend has responded at all: the message must already
      // be visible, the empty-state prompt gone, input disabled, and a
      // real (not fabricated/percentage) loading indicator shown.
      await page.waitForSelector('.ai-chat-message--user');
      const userBubbleText = await page.textContent('.ai-chat-message--user');
      assert.strictEqual(userBubbleText, 'Create an API to search hotels in Cox\'s Bazar.');
      assert.strictEqual(await page.$eval('#chat-empty', (el) => el.hidden), true);
      assert.strictEqual(await page.$eval('#ai-input', (el) => el.disabled), true);
      assert.strictEqual(await page.$eval('#send-btn', (el) => el.disabled), true);

      const statusHidden = await page.$eval('#status-area', (el) => el.hidden);
      assert.strictEqual(statusHidden, false, 'expected a genuine loading/processing indicator while the request is in flight');
      const statusText = await page.textContent('#status-area');
      assert.ok(statusText.toLowerCase().includes('understanding'), 'expected an honest status message, not silence');
      assert.ok(!/%/.test(statusText), 'must never show a fake percentage');

      // The three previously-broken containers must stay genuinely hidden
      // (zero visible box), not just marked hidden="" while still painted —
      // the actual CSS bug this test also guards against.
      for (const id of ['confirm-area', 'error-area', 'result-area']) {
        const box = await page.locator(`#${id}`).boundingBox();
        assert.strictEqual(box, null, `#${id} must not be rendered while hidden`);
      }

      assert.strictEqual(calls.filter((c) => c.url.endsWith('/api/ai-creator/sessions') && c.method === 'POST').length, 1);

      // Now let the real backend response shape arrive and confirm the
      // pending bubble is reconciled into the real transcript, not
      // duplicated.
      releaseCreate();
      await page.waitForSelector('#confirm-area:not([hidden])');
      const userBubbles = await page.locator('.ai-chat-message--user').count();
      assert.strictEqual(userBubbles, 1, 'the message must not be rendered twice once the real session arrives');
      assert.strictEqual(await page.$eval('#status-area', (el) => el.hidden), false);
      assert.ok((await page.textContent('#status-area')).includes('confirmation'));
    });
  });

  await test('a failed session request shows a real error, clears the loading state, and restores Send/input', async () => {
    const matchers = [{
      test: (url, m) => url.endsWith('/api/ai-creator/sessions') && m === 'POST',
      respond: (route) => fulfillJson(route, 500, { success: false, message: 'The AI provider is unavailable right now.' })
    }];

    await withPage({ matchers }, async (page) => {
      await page.fill('#ai-input', 'Create an API to do something.');
      await page.click('#send-btn');

      await page.waitForSelector('#error-area:not([hidden])');
      const errorText = await page.textContent('#error-area');
      assert.ok(errorText.includes('The AI provider is unavailable right now.'), 'expected the real backend error message, not a generic one');

      const bodyText = await page.textContent('body');
      assert.ok(!bodyText.includes('understood'), 'must not render a confirmation/success area for a failed request');
      assert.strictEqual(await page.$eval('#confirm-area', (el) => el.hidden), true);

      // Loading state fully cleared, controls restored.
      assert.strictEqual(await page.$eval('#status-area', (el) => el.hidden), true);
      assert.strictEqual(await page.$eval('#ai-input', (el) => el.disabled), false);
      assert.strictEqual(await page.$eval('#send-btn', (el) => el.disabled), false);
    });
  });

  await test('confirmation area renders a flight-shaped intent (origin/destination) generically', async () => {
    const session = makeSession({ intent: FLIGHT_INTENT });
    const matchers = [{ test: (url, m) => url.endsWith('/api/ai-creator/sessions') && m === 'POST', respond: (route) => fulfillJson(route, 201, { success: true, ...session }) }];

    await withPage({ matchers }, async (page) => {
      await page.fill('#ai-input', 'Create an API to search for flights from Dhaka to Dubai.');
      await page.click('#send-btn');
      await page.waitForSelector('#confirm-area:not([hidden])');

      const text = await page.textContent('#confirm-area');
      assert.ok(text.includes('Origin'), 'expected the Origin label from the backend intent');
      assert.ok(text.includes('Dhaka'));
      assert.ok(text.includes('Destination'));
      assert.ok(text.includes('Dubai'));
      // No site-confirmation gate for this fixture (needsConfirmation: false).
      assert.ok(text.includes('Confirm & Generate') || text.includes('Confirm &amp; Generate'));
    });
  });

  await test('confirmation area renders a completely different (hotel) parameter set with the SAME code path, and gates on needsConfirmation', async () => {
    const session = makeSession({ intent: HOTEL_INTENT });
    const matchers = [{ test: (url, m) => url.endsWith('/api/ai-creator/sessions') && m === 'POST', respond: (route) => fulfillJson(route, 201, { success: true, ...session }) }];

    await withPage({ matchers }, async (page) => {
      await page.fill('#ai-input', "Create an API to search hotels in Cox's Bazar.");
      await page.click('#send-btn');
      await page.waitForSelector('#confirm-area:not([hidden])');

      const text = await page.textContent('#confirm-area');
      assert.ok(text.includes('City'));
      assert.ok(text.includes("Cox's Bazar"));
      assert.ok(text.includes('Check-in'));
      assert.ok(text.includes('Number of nights'));
      assert.ok(text.includes('Booking.com'));

      // needsConfirmation: true — the Generate button must NOT be offered
      // until the explicit site-confirmation action is taken.
      const generateVisible = await page.isVisible('#generate-btn');
      assert.strictEqual(generateVisible, false, 'Generate must be gated behind explicit site confirmation');
      const warningVisible = await page.isVisible('.ai-site-warning');
      assert.ok(warningVisible, 'expected an explicit site-confirmation warning');

      await page.click('#confirm-site-btn');
      await page.waitForSelector('#generate-btn');
      assert.ok(await page.isVisible('#generate-btn'), 'Generate should appear once the site is explicitly confirmed');
    });
  });

  await test('a follow-up message calls POST /api/ai-creator/sessions/:id/messages, not a new session', async () => {
    const initialSession = makeSession({ sessionId: 42, intent: FLIGHT_INTENT });
    const correctedIntent = { ...FLIGHT_INTENT, parameters: [{ ...FLIGHT_INTENT.parameters[0], value: 'Chittagong' }, FLIGHT_INTENT.parameters[1]] };
    const followUpSession = makeSession({ sessionId: 42, intent: correctedIntent });

    const matchers = [
      { test: (url, m) => url.endsWith('/api/ai-creator/sessions') && m === 'POST', respond: (route) => fulfillJson(route, 201, { success: true, ...initialSession }) },
      {
        test: (url, m) => url.endsWith('/api/ai-creator/sessions/42/messages') && m === 'POST',
        respond: (route, request) => {
          const body = JSON.parse(request.postData());
          assert.strictEqual(body.message, 'Actually use Chittagong as the origin.');
          return fulfillJson(route, 200, { success: true, ...followUpSession });
        }
      }
    ];

    await withPage({ matchers }, async (page, calls) => {
      await page.fill('#ai-input', 'Create an API to search flights from Dhaka to Dubai.');
      await page.click('#send-btn');
      await page.waitForSelector('#confirm-area:not([hidden])');

      await page.fill('#ai-input', 'Actually use Chittagong as the origin.');
      await page.click('#send-btn');
      await page.waitForFunction(() => document.querySelector('#confirm-area')?.textContent.includes('Chittagong'));

      const followUpCalls = calls.filter((c) => c.url.includes('/messages'));
      assert.strictEqual(followUpCalls.length, 1);
      const newSessionCalls = calls.filter((c) => c.url.endsWith('/api/ai-creator/sessions') && c.method === 'POST');
      assert.strictEqual(newSessionCalls.length, 1, 'a follow-up must not create a second session');
    });
  });

  await test('Generate calls POST .../generate, polls GET .../sessions/:id while generating, and shows the real success result', async () => {
    const confirmedSession = makeSession({ sessionId: 7, intent: FLIGHT_INTENT });
    let releaseGenerate;
    const generateGate = new Promise((resolve) => { releaseGenerate = resolve; });

    const myApiRecord = {
      id: 501, ownerId: 1, workflowId: '77', name: 'Search for flights', version: 'v1.0', method: 'POST',
      endpoint: '/api/workflows/77/run', description: 'Generated by the AI API Creator', parameters: FLIGHT_INTENT.parameters,
      price: 0, published: false, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString()
    };

    const matchers = [
      { test: (url, m) => url.endsWith('/api/ai-creator/sessions') && m === 'POST', respond: (route) => fulfillJson(route, 201, { success: true, ...confirmedSession }) },
      {
        test: (url, m) => url.endsWith('/api/ai-creator/sessions/7/generate') && m === 'POST',
        respond: async (route) => {
          await generateGate; // held open until the test explicitly releases it
          await fulfillJson(route, 200, {
            success: true, ...makeSession({ sessionId: 7, status: 'completed', intent: FLIGHT_INTENT, generatedWorkflowId: '77' }),
            workflowId: '77', myApiId: 501, endpoint: '/api/workflows/77/run', method: 'POST', stepCount: 2
          });
        }
      },
      {
        test: (url, m) => url.endsWith('/api/ai-creator/sessions/7') && m === 'GET',
        respond: (route) => fulfillJson(route, 200, { success: true, ...makeSession({ sessionId: 7, status: 'generating', intent: FLIGHT_INTENT }) })
      },
      {
        test: (url, m) => url.endsWith('/api/my-apis/501') && m === 'GET',
        respond: (route) => fulfillJson(route, 200, myApiRecord)
      }
    ];

    await withPage({ matchers }, async (page, calls) => {
      await page.fill('#ai-input', 'Create an API to search flights from Dhaka to Dubai.');
      await page.click('#send-btn');
      await page.waitForSelector('#generate-btn');
      await page.click('#generate-btn');

      // While the generate POST is deliberately held open, the status area
      // must show the real backend 'generating' state (no fake progress %).
      await page.waitForSelector('#status-area:not([hidden])');
      const statusText = await page.textContent('#status-area');
      assert.ok(statusText.toLowerCase().includes('generat'), 'expected a "generating" status message');
      assert.ok(!/%/.test(statusText), 'must never show a fake percentage');

      // Duplicate-submission prevention: Generate is gone/disabled once busy.
      const generateStillClickable = await page.isVisible('#generate-btn');
      assert.strictEqual(generateStillClickable, false, 'Generate must not be re-offered while a generation is already in flight');

      // Let one real poll tick (POLL_INTERVAL_MS in ai-creator.js) fire
      // before releasing the held-open /generate response, so the GET
      // .../sessions/:id polling path is actually exercised, not assumed.
      await page.waitForTimeout(6300);
      releaseGenerate();
      await page.waitForSelector('#result-area:not([hidden])');
      await page.waitForFunction(() => document.querySelector('#result-area')?.textContent.includes('generated successfully'));

      const pollCalls = calls.filter((c) => c.url.endsWith('/api/ai-creator/sessions/7') && c.method === 'GET');
      assert.ok(pollCalls.length >= 1, 'expected at least one GET .../sessions/:id poll during generation');

      const resultText = await page.textContent('#result-area');
      assert.ok(resultText.includes('/api/workflows/77/run'), 'expected the real endpoint from the backend response');
      assert.ok(await page.isVisible('#run-api-btn'));
      assert.ok(await page.isVisible('#test-api-btn'));
      assert.ok(await page.isVisible('#publish-api-btn'));
      assert.ok(await page.isVisible('#copy-json-btn'));
      assert.ok(await page.isVisible('#download-json-btn'));

      const jsonBlock = await page.textContent('.ai-json-block');
      const parsed = JSON.parse(jsonBlock);
      assert.strictEqual(parsed.id, 501);
      assert.strictEqual(parsed.endpoint, '/api/workflows/77/run');
      // JSON output must never leak internal replay details.
      assert.ok(!jsonBlock.includes('locators'));
      assert.ok(!jsonBlock.includes('selector'));
    });
  });

  // --- JSON results panel ----------------------------------------------

  await test('extracted results render in a dedicated JSON panel: count header, metadata, and pretty-printed ARBITRARY JSON', async () => {
    await withPage({ matchers: completedGenerateMatchers({ sessionId: 20, myApiId: 520, workflowId: 88, results: GENERIC_RESULTS }) }, async (page) => {
      await generateThenComplete(page);
      await page.waitForSelector('.ai-results-panel');

      // Count header from results.totalFound.
      const count = await page.textContent('.ai-results-count');
      assert.ok(/\b3 results captured\b/.test(count), `expected "3 results captured", got "${count}"`);

      // Extraction metadata surfaced.
      const meta = await page.textContent('.ai-results-meta');
      assert.ok(/Method:\s*dom/i.test(meta), 'expected extraction method in metadata');
      assert.ok(/Confidence:\s*70%/.test(meta), 'expected confidence % in metadata');
      assert.ok(meta.includes('https://example.test/results'), 'expected the source URL in metadata');

      // The dataset JSON is the REAL data, pretty-printed, and rendered
      // generically (arbitrary field names, no per-field frontend code).
      const jsonText = await page.textContent('.ai-results-json');
      assert.ok(/\n\s{2,}/.test(jsonText), 'expected indented, pretty-printed JSON');
      const parsed = JSON.parse(jsonText);
      assert.deepStrictEqual(parsed, GENERIC_RESULTS.data, 'the panel must render the exact dataset the backend returned');
      assert.ok(jsonText.includes('alpha') && jsonText.includes('gamma'), 'arbitrary fields must render verbatim');

      // Dataset copy/download controls exist alongside the existing API controls.
      assert.ok(await page.isVisible('#copy-results-btn'));
      assert.ok(await page.isVisible('#download-results-btn'));

      // Existing API-definition block and controls are preserved and separate.
      assert.ok(await page.isVisible('#run-api-btn'));
      assert.ok(await page.isVisible('#download-json-btn'));
      const apiDef = JSON.parse(await page.textContent('.ai-json-block'));
      assert.strictEqual(apiDef.id, 520, 'the existing API-definition JSON block must remain intact and distinct from the results panel');

      // Copy JSON copies the dataset (not the API definition).
      await page.evaluate(() => {
        window.__copied = null;
        Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: (t) => { window.__copied = t; return Promise.resolve(); } } });
      });
      await page.click('#copy-results-btn');
      const copied = await page.evaluate(() => window.__copied);
      assert.ok(copied, 'expected Copy JSON to write to the clipboard');
      assert.deepStrictEqual(JSON.parse(copied), GENERIC_RESULTS.data, 'Copy JSON must copy the extracted dataset');
    });
  });

  await test('the results Download JSON control downloads the extracted dataset', async () => {
    await withPage({ matchers: completedGenerateMatchers({ sessionId: 21, myApiId: 521, workflowId: 89, results: GENERIC_RESULTS }) }, async (page) => {
      await generateThenComplete(page);
      await page.waitForSelector('#download-results-btn');
      const [download] = await Promise.all([
        page.waitForEvent('download'),
        page.click('#download-results-btn')
      ]);
      assert.ok(/results/i.test(download.suggestedFilename()), `expected a results filename, got ${download.suggestedFilename()}`);
    });
  });

  await test('no structured results → an honest empty state, never fabricated JSON', async () => {
    await withPage({ matchers: completedGenerateMatchers({ sessionId: 22, myApiId: 522, workflowId: 90, results: { data: [], totalFound: 0, confidence: 0, extractionMethod: 'none', truncated: false, source: null } }) }, async (page) => {
      await generateThenComplete(page);
      await page.waitForSelector('.ai-results-panel--empty');

      const emptyText = await page.textContent('.ai-results-panel--empty');
      assert.ok(/no results captured/i.test(emptyText), 'expected an honest no-results message');

      // Crucially: NO results JSON block, so nothing fake is shown.
      const jsonPanels = await page.locator('.ai-results-json').count();
      assert.strictEqual(jsonPanels, 0, 'an empty result set must not render a JSON dataset block at all');
      // And no dataset copy/download controls to act on a nonexistent dataset.
      assert.strictEqual(await page.locator('#copy-results-btn').count(), 0);

      // The generated API itself still rendered (generation succeeded).
      assert.ok(await page.isVisible('#run-api-btn'));
    });
  });

  await test('re-running via Run API with a new value refreshes the results panel (demo parity)', async () => {
    const runResults = { success: true, message: 'Workflow completed successfully.', data: [{ alpha: 'fresh-1' }, { alpha: 'fresh-2' }], execution: { totalFound: 2, truncated: false, stepsExecuted: 3 }, extractionMethod: 'dom', confidence: 0.8, finalUrl: 'https://example.test/results?x=2', parametersApplied: {} };
    const matchers = [
      ...completedGenerateMatchers({ sessionId: 23, myApiId: 523, workflowId: 91, results: GENERIC_RESULTS }),
      { test: (url, m) => url.endsWith('/api/workflows/91/run') && m === 'POST', respond: (route) => fulfillJson(route, 200, runResults) }
    ];
    await withPage({ matchers }, async (page) => {
      await generateThenComplete(page);
      await page.waitForSelector('.ai-results-panel');
      assert.ok(/3 results captured/.test(await page.textContent('.ai-results-count')));

      await page.click('#run-api-btn');
      // Panel updates to the fresh run's dataset/count.
      await page.waitForFunction(() => /2 results captured/.test(document.querySelector('.ai-results-count')?.textContent || ''));
      const parsed = JSON.parse(await page.textContent('.ai-results-json'));
      assert.deepStrictEqual(parsed, runResults.data, 'the panel should reflect the freshly re-run dataset');
    });
  });

  await test('a failed generation (e.g. a login wall) shows a real error, never a fake success message', async () => {
    const confirmedSession = makeSession({ sessionId: 9, intent: FLIGHT_INTENT });
    const failedSession = makeSession({
      sessionId: 9, status: 'failed', intent: FLIGHT_INTENT,
      extraMessages: [{ role: 'system', type: 'error', text: 'This page requires logging in before continuing.', at: new Date().toISOString() }]
    });

    const matchers = [
      { test: (url, m) => url.endsWith('/api/ai-creator/sessions') && m === 'POST', respond: (route) => fulfillJson(route, 201, { success: true, ...confirmedSession }) },
      {
        test: (url, m) => url.endsWith('/api/ai-creator/sessions/9/generate') && m === 'POST',
        respond: (route) => fulfillJson(route, 422, { success: false, ...failedSession, message: 'This page requires logging in before continuing.', agentResult: { stopReason: 'login_wall', stepCount: 1 } })
      }
    ];

    await withPage({ matchers }, async (page) => {
      await page.fill('#ai-input', 'Create an API to search flights from Dhaka to Dubai.');
      await page.click('#send-btn');
      await page.waitForSelector('#generate-btn');
      await page.click('#generate-btn');

      await page.waitForSelector('#error-area:not([hidden])');
      const errorText = await page.textContent('#error-area');
      assert.ok(errorText.includes('logging in'), 'expected the real backend error message');

      const bodyText = await page.textContent('body');
      assert.ok(!bodyText.includes('generated successfully'), 'must never claim success after a failed generation');
      const resultHidden = await page.$eval('#result-area', (el) => el.hidden);
      assert.strictEqual(resultHidden, true);
    });
  });

  await test('voice input (SpeechRecognition) places the transcript into the same textbox, editable, without auto-sending', async () => {
    await withPage({ speech: 'fake' }, async (page) => {
      await page.click('#mic-btn');
      await page.waitForFunction(() => window.__recognitionInstances && window.__recognitionInstances.length === 1);

      await page.evaluate(() => {
        const ev = new Event('result');
        ev.results = [[{ transcript: 'Create an API to find laptops under 80000 taka' }]];
        window.__recognitionInstances[0].dispatchEvent(ev);
      });

      const inputValue = await page.inputValue('#ai-input');
      assert.strictEqual(inputValue, 'Create an API to find laptops under 80000 taka');

      // Not auto-sent — no session has been created from voice input alone.
      const confirmHidden = await page.$eval('#confirm-area', (el) => el.hidden);
      assert.strictEqual(confirmHidden, true);
    });
  });

  await test('unsupported SpeechRecognition disables the mic button and shows a fallback message, typed input still works', async () => {
    const matchers = [{ test: (url, m) => url.endsWith('/api/ai-creator/sessions') && m === 'POST', respond: (route) => fulfillJson(route, 201, { success: true, ...makeSession({ intent: FLIGHT_INTENT }) }) }];
    await withPage({ speech: 'unsupported', matchers }, async (page) => {
      const micDisabled = await page.$eval('#mic-btn', (el) => el.disabled);
      assert.strictEqual(micDisabled, true);
      const hintHidden = await page.$eval('#voice-hint', (el) => el.hidden);
      assert.strictEqual(hintHidden, false);

      // Typed input must be entirely unaffected.
      await page.fill('#ai-input', 'Create an API to search Amazon for wireless headphones.');
      await page.click('#send-btn');
      await page.waitForSelector('#confirm-area:not([hidden])');
    });
  });

  await test('duplicate submissions are prevented while a request is in flight', async () => {
    let releaseCreate;
    const gate = new Promise((resolve) => { releaseCreate = resolve; });
    const matchers = [{
      test: (url, m) => url.endsWith('/api/ai-creator/sessions') && m === 'POST',
      respond: async (route) => { await gate; await fulfillJson(route, 201, { success: true, ...makeSession({ intent: FLIGHT_INTENT }) }); }
    }];

    await withPage({ matchers }, async (page, calls) => {
      await page.fill('#ai-input', 'Create an API to search for flights from Dhaka to Dubai.');
      await page.click('#send-btn');
      await page.waitForFunction(() => document.getElementById('send-btn').disabled === true);

      // A second click while busy must not fire a second request.
      await page.click('#send-btn', { force: true }).catch(() => {});
      releaseCreate();
      await page.waitForSelector('#confirm-area:not([hidden])');

      const createCalls = calls.filter((c) => c.url.endsWith('/api/ai-creator/sessions') && c.method === 'POST');
      assert.strictEqual(createCalls.length, 1, 'expected exactly one create-session call despite the duplicate click attempt');
    });
  });

  await browser.close();

  const failed = results.filter((r) => !r.ok);
  console.log(`\n${results.length - failed.length}/${results.length} passed`);
  if (failed.length) {
    process.exitCode = 1;
  }
};

run();
