// Server-side equivalent of extension/content/content.js's
// getLocatorCandidates(), but for READING a live page rather than recording
// a human's interaction with it. This is the foundation for the AI API
// Creator's browser agent (V2 Phase 2, not yet built): given a Playwright
// page, produce a compact, structured description of the interactive
// elements on it, so an LLM can be told "here are the elements you can act
// on" instead of being handed raw page HTML (which would be enormous, mostly
// irrelevant, and — since page content is untrusted input from whatever site
// the agent visits — a prompt-injection surface).
//
// Deliberately generic: nothing in this file names a specific website. Every
// element is described purely from its own DOM/ARIA semantics, the same
// signals content.js already uses to build resilient replay locators
// (role/label/placeholder/aria-label/data-testid/name/id), so a snapshot
// element's `locators` array is directly consumable by
// replayEngine.locatorFromCandidate without any translation step.
//
// Runs its DOM walk entirely inside the page via page.evaluate — no Node/
// Playwright APIs are reachable there, matching the pattern already
// established by backend/services/extraction/domExtractor.js.
const MAX_ELEMENTS = 150;

// Same judgment content.js's looksAutoGenerated() applies when recording —
// duplicated here (not imported) because this function has to run INSIDE
// page.evaluate, where only plain browser APIs are reachable, not any
// Node-side module.
const looksAutoGeneratedSource = `
  (raw) => {
    if (!raw) return true;
    const trimmed = String(raw).trim();
    if (!trimmed) return true;
    if (/\\d{3,}/.test(trimmed) || /^(mui|radix|chakra|css|ember|react|ng|v-|data-v)[-:]/i.test(trimmed)) return true;
    const words = trimmed
      .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
      .replace(/[_-]+/g, ' ')
      .replace(/[^a-zA-Z0-9\\s]/g, ' ')
      .trim()
      .split(/\\s+/)
      .filter(Boolean);
    if (words.length === 0) return true;
    if (words.length > 1) return false;
    const word = words[0].toLowerCase();
    if (['input', 'field', 'value', 'text', 'container', 'wrapper', 'div', 'span', 'item', 'box'].includes(word)) return true;
    if (word.length >= 6) {
      const vowels = (word.match(/[aeiou]/gi) || []).length;
      if (vowels / word.length < 0.2) return true;
    }
    return false;
  }
`;

// Same redaction judgment as content.js's isSensitiveField()/REDACTED_VALUE
// — a snapshot may end up inside an LLM prompt, so a sensitive field's live
// value must never be included, only enough to know it exists (so the agent
// can recognize "this looks like a login wall" and stop, per the
// requirement to fail gracefully on auth walls rather than attempt them).
const isSensitiveFieldSource = `
  (el) => {
    if (el.tagName === 'INPUT' && el.type === 'password') return true;
    const probe = [el.name, el.id, el.autocomplete, el.getAttribute('aria-label'), el.placeholder]
      .filter(Boolean).join(' ').toLowerCase();
    return /card[-_]?number|cvv|cvc|ssn|social[-_]?security|passport|\\botp\\b|one[-_]?time[-_]?passcode/.test(probe);
  }
`;

// Implicit ARIA role for standard <input> types, matching content.js's
// INPUT_TYPE_TO_ROLE exactly.
const INPUT_TYPE_TO_ROLE_SOURCE = `{
  checkbox: 'checkbox', radio: 'radio', range: 'slider', number: 'spinbutton',
  search: 'searchbox', email: 'textbox', tel: 'textbox', url: 'textbox',
  text: 'textbox', password: 'textbox', button: 'button', submit: 'button',
  reset: 'button', image: 'button'
}`;

// Built as a string and assembled with `new Function` inside page.evaluate
// (see buildSnapshotInPage) rather than passed as separate closures, because
// Playwright's page.evaluate serializes its argument across the browser/Node
// boundary — function values don't survive that trip, only plain data and a
// single function body do.
const buildSnapshotInPage = ({ maxElements, looksAutoGeneratedSrc, isSensitiveFieldSrc, inputTypeToRoleSrc }) => {
  // Each *Src string's own text starts with a newline (template literals in
  // the Node-side source above). "return" immediately followed by a newline
  // triggers automatic semicolon insertion — `return\n(el) => {...}` becomes
  // `return; (el) => {...};`, silently handing back undefined instead of the
  // function. Keeping "(" on the same line as "return" prevents that.
  /* eslint-disable no-new-func */
  const looksAutoGenerated = new Function(`return (${looksAutoGeneratedSrc})`)();
  const isSensitiveField = new Function(`return (${isSensitiveFieldSrc})`)();
  const INPUT_TYPE_TO_ROLE = new Function(`return (${inputTypeToRoleSrc})`)();
  /* eslint-enable no-new-func */

  const isVisible = (el) => {
    if (!(el instanceof Element)) return false;
    const rect = el.getBoundingClientRect();
    if (rect.width === 0 || rect.height === 0) return false;
    const style = window.getComputedStyle(el);
    return style.visibility !== 'hidden' && style.display !== 'none' && Number(style.opacity) !== 0;
  };

  const inViewport = (el) => {
    const rect = el.getBoundingClientRect();
    return rect.bottom > 0 && rect.right > 0
      && rect.top < (window.innerHeight || document.documentElement.clientHeight)
      && rect.left < (window.innerWidth || document.documentElement.clientWidth);
  };

  const getVisibleText = (el) => (el.innerText || el.textContent || '').trim().replace(/\s+/g, ' ').slice(0, 120);

  const getLabelText = (el) => {
    if (el.labels && el.labels.length) return getVisibleText(el.labels[0]);
    const id = el.getAttribute('id');
    if (id) {
      const labelFor = document.querySelector(`label[for="${CSS.escape(id)}"]`);
      if (labelFor) return getVisibleText(labelFor);
    }
    return null;
  };

  const getAriaLabelledByText = (el) => {
    const ids = (el.getAttribute('aria-labelledby') || '').split(/\s+/).filter(Boolean);
    if (!ids.length) return null;
    const text = ids.map((id) => {
      const ref = document.getElementById(id);
      return ref ? getVisibleText(ref) : '';
    }).filter(Boolean).join(' ');
    return text || null;
  };

  const INTERACTIVE_SELECTOR = [
    'input:not([type="hidden"])', 'textarea', 'select', 'button',
    'a[href]', 'summary', '[role="button"]', '[role="link"]', '[role="checkbox"]',
    '[role="radio"]', '[role="combobox"]', '[role="textbox"]', '[role="searchbox"]',
    '[role="tab"]', '[role="menuitem"]', '[role="option"]',
    '[onclick]', '[tabindex]:not([tabindex="-1"])'
  ].join(', ');

  const buildLocators = (el, tag, accessibleName) => {
    const locators = [];

    const testId = el.getAttribute('data-testid') || el.getAttribute('data-test-id')
      || el.getAttribute('data-test') || el.getAttribute('data-qa');
    if (testId) {
      locators.push({ strategy: 'css', value: `[data-testid="${CSS.escape(testId)}"], [data-test-id="${CSS.escape(testId)}"], [data-test="${CSS.escape(testId)}"], [data-qa="${CSS.escape(testId)}"]` });
    }

    if (el.id && !looksAutoGenerated(el.id)) {
      locators.push({ strategy: 'css', value: `#${CSS.escape(el.id)}` });
    }

    const name = el.getAttribute('name');
    if (name) {
      locators.push({ strategy: 'css', value: `${tag}[name="${CSS.escape(name)}"]` });
    }

    const labelText = getLabelText(el);
    if (labelText && labelText.length <= 100) {
      locators.push({ strategy: 'label', value: labelText });
    }

    const placeholder = el.getAttribute('placeholder');
    if (placeholder) {
      locators.push({ strategy: 'css', value: `${tag}[placeholder="${CSS.escape(placeholder)}"]` });
    }

    const implicitRole = el.getAttribute('role')
      || (tag === 'a' ? 'link' : null)
      || (tag === 'button' ? 'button' : null)
      || (tag === 'summary' ? 'button' : null)
      || (tag === 'textarea' ? 'textbox' : null)
      || (tag === 'select' ? ((el.multiple || Number(el.size) > 1) ? 'listbox' : 'combobox') : null)
      || (tag === 'input' ? (INPUT_TYPE_TO_ROLE[el.type] || null) : null);

    if (implicitRole && accessibleName) {
      locators.push({ strategy: 'role', role: implicitRole, name: accessibleName });
    }

    if (accessibleName && (tag === 'button' || tag === 'a' || tag === 'summary')) {
      locators.push({ strategy: 'text', value: accessibleName, tag });
    }

    // Guaranteed fallback so every returned element has at least one
    // locator, even with no semantic attributes at all — a structural CSS
    // path is still better than nothing, it's just listed last because it's
    // the least resilient to page changes.
    if (!locators.length) {
      const classes = (typeof el.className === 'string' ? el.className.trim().split(/\s+/).filter(Boolean) : []);
      locators.push({ strategy: 'css', value: classes.length ? `${tag}.${classes.slice(0, 3).join('.')}` : tag });
    }

    return locators;
  };

  const candidates = Array.from(document.querySelectorAll(INTERACTIVE_SELECTOR))
    .filter((el) => isVisible(el) && !el.disabled);

  const totalFound = candidates.length;
  const limited = candidates.slice(0, maxElements);

  const elements = limited.map((el, index) => {
    const tag = el.tagName.toLowerCase();
    const ariaLabel = el.getAttribute('aria-label');
    const labelText = getLabelText(el);
    const accessibleName = (
      ariaLabel
      || getAriaLabelledByText(el)
      || labelText
      || getVisibleText(el)
      || el.getAttribute('value')
      || ''
    ).slice(0, 80) || null;

    const sensitive = isSensitiveField(el);
    let value = null;
    if (!sensitive) {
      if (tag === 'input' || tag === 'textarea') value = el.value || null;
      else if (tag === 'select') value = el.value || null;
    }

    return {
      ref: `e${index}`,
      tag,
      type: el.getAttribute('type') || null,
      role: el.getAttribute('role') || null,
      name: accessibleName,
      label: labelText,
      placeholder: el.getAttribute('placeholder') || null,
      value,
      sensitive,
      checked: (tag === 'input' && (el.type === 'checkbox' || el.type === 'radio')) ? Boolean(el.checked) : null,
      inViewport: inViewport(el),
      locators: buildLocators(el, tag, accessibleName)
    };
  });

  return {
    url: window.location.href,
    title: document.title,
    elements,
    totalFound,
    truncated: totalFound > limited.length
  };
};

// Builds a compact, LLM-ready snapshot of the given Playwright page's
// currently interactive elements. Read-only — takes no action on the page.
const buildPageSnapshot = async (page, { maxElements = MAX_ELEMENTS } = {}) => page.evaluate(buildSnapshotInPage, {
  maxElements,
  looksAutoGeneratedSrc: looksAutoGeneratedSource,
  isSensitiveFieldSrc: isSensitiveFieldSource,
  inputTypeToRoleSrc: INPUT_TYPE_TO_ROLE_SOURCE
});

module.exports = { buildPageSnapshot, MAX_ELEMENTS };
