/**
 * Single source of truth for the backend base URL. This is an unbundled
 * Chrome extension (no webpack/vite build step), so there's no real
 * process.env available in browser JS — this file is generated by
 * extension/shared/generate-config.js from the FORGEFLOW_API_BASE
 * environment variable. Do not hand-edit; re-run the generator instead:
 *
 *   FORGEFLOW_API_BASE=https://your-app.up.railway.app node extension/shared/generate-config.js
 */
// `self` (not `window`) so this same file loads unmodified both as a page
// <script> tag (where self === window) and via importScripts() in the
// background service worker (background/service-worker.js), which has no
// `window` global at all.
self.FORGEFLOW_API_BASE = 'http://localhost:5000';
