#!/usr/bin/env node
/**
 * Regenerates extension/shared/config.js from the FORGEFLOW_API_BASE
 * environment variable. This is an unbundled Chrome extension (no
 * webpack/vite build step) so there's no real process.env available in
 * browser JS — this script is the environment-variable equivalent for this
 * codebase. Run it before packaging to point the extension at a deployed
 * backend (e.g. Railway) instead of localhost.
 *
 * Usage:
 *   FORGEFLOW_API_BASE=https://your-app.up.railway.app node extension/shared/generate-config.js
 *
 * Running it with no FORGEFLOW_API_BASE set (or not running it at all)
 * regenerates the committed localhost default — local development is
 * unaffected either way.
 */
const fs = require('fs');
const path = require('path');

const apiBase = process.env.FORGEFLOW_API_BASE || 'http://localhost:5000';
const outPath = path.join(__dirname, 'config.js');

const contents = `/**
 * Single source of truth for the backend base URL. This is an unbundled
 * Chrome extension (no webpack/vite build step), so there's no real
 * process.env available in browser JS — this file is generated by
 * extension/shared/generate-config.js from the FORGEFLOW_API_BASE
 * environment variable. Do not hand-edit; re-run the generator instead:
 *
 *   FORGEFLOW_API_BASE=https://your-app.up.railway.app node extension/shared/generate-config.js
 */
// \`self\` (not \`window\`) so this same file loads unmodified both as a page
// <script> tag (where self === window) and via importScripts() in the
// background service worker (background/service-worker.js), which has no
// \`window\` global at all.
self.FORGEFLOW_API_BASE = '${apiBase}';
`;

fs.writeFileSync(outPath, contents);
console.log(`[generate-config] wrote extension/shared/config.js -> FORGEFLOW_API_BASE=${apiBase}`);
